name: Runner Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name=${{ runner.name }}"
      - run: echo "os=${{ runner.os }}"
      - run: echo "arch=${{ runner.arch }}"
      - run: echo "temp=${{ runner.temp }}"
      - run: echo "debug=${{ runner.debug }}"